### ISSUE TITLE
Issue: Exceptionin thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by jawlitkp** [anshooarora/extentreports-java#476]
Hi Anshoo,

I got below error when i ran more than 800 test cases.

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuffer.append(Unknown Source)
	at java.util.regex.Matcher.appendReplacement(Unknown Source)
	at java.util.regex.Matcher.replaceAll(Unknown Source)
	at java.lang.String.replace(Unknown Source)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:174)
	at com.relevantcodes.extentreports.Report.flush(Report.java:464)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:902)

**Comment by anshooarora** [comment]
On line 174 of HTMLReporter, a replace("\t") is performed.  Although if your file is large, it will consume a lot of memory but 800 test cases is not a lot to cause this.  How much RAM do you have on the system?  I have removed the replace altogether though and uploaded the new jars but its very strange to see this issue.

**Comment by jawlitkp** [comment]
4.00 GB. i will try with the new jar next week.

Thanks!

**Comment by anshooarora** [comment]
Are you still having this issue?  It does sound machine specific as I remember you had another performance issue on it.  Or maybe your normal workstation is too quick for your Windows box to keep up :)

**Comment by jawlitkp** [comment]
No i don't see this issue lately

**Comment by johnealscawaling** [comment]
What version is this occurring? I'm using 2.41.2 and I'm encountering the same issue.

I'm having issues with line 173 of HTMLReporter.class

This specific line

template.process(templateMap, out);
