### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: com.relevantcodes.extentreports.model.Test.setLog(Lcom/relevantcodes/extentreports/model/Log;)

### ISSUE THREAD

**Issue by SHASHIJB** [anshooarora/extentreports-java#557]
HI Anshoo,

Getting the following error message 

Exception in thread "main" java.lang.NoSuchMethodError: com.relevantcodes.extentreports.model.Test.setLog(Lcom/relevantcodes/extentreports/model/Log;)V
    at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:95)
    at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:176)
    at web.mobile.test.DriverScript.start(DriverScript.java:148)
    at main.Intial.main(Intial.java:73)

Currently i m using this project in my gradle project 
compile 'com.relevantcodes:extentreports:2.40.2'.

I am using Gradle as build tool. Please help me to resolve the issue.

Currently i have implemented my project using Hybrid Frawework ( data-driven + keyword driven) .

-----------build.Gradle _ File

/*
- This build file was auto generated by running the Gradle 'init' task
- by 'skjb0001' at '7/7/16 3:24 PM' with Gradle 2.9
  *
- This generated file contains a sample Java project to get you started.
- For more details take a look at the Java Quickstart chapter in the Gradle
- user guide available at https://docs.gradle.org/2.9/userguide/tutorial_java_projects.html
  */

// Apply the java plugin to add support for Java
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'maven'
apply plugin: 'application'

mainClassName = 'main.Intial'
// In this section you declare where to find the dependencies of your project
repositories {
    // Use 'jcenter' for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
   flatDir {
        dirs 'libs'
    }  
     //jcenter()
     mavenCentral()
    //mavenLocal()

}

// In this section you declare the dependencies for your production and test code
dependencies {
    // The production code uses the SLF4J logging API at testCompile time
    //compile 'org.slf4j:slf4j-api:1.7.13'

```
//--------
//runtime ":extentmerge"
//runtime name:'extentmerge'
//--------

// Declare the dependency for your favourite test framework you want to use in your tests.
// TestNG is also supported by the Gradle Test task. Just change the
// testCompile dependency to testCompile 'org.testng:testng:6.8.1' and add
// 'test.useTestNG()' to your build script.
 //testCompile files("extentmerge.jar")
//testCompile files('libs/something_local.jar')
// -- Exteranl method to include jar from library path 
compile fileTree(dir: 'libs', include: ['*.jar'])
compile 'junit:junit:4.12'
compile 'org.apache.commons:commons-lang3:3.3.2'
compile 'commons-logging:commons-logging:1.1.3'
compile 'net.sourceforge.cssparser:cssparser:0.9.14'
compile 'dom4j:dom4j:1.1'
compile 'com.google.code.gson:gson:2.2.4'
compile 'com.google.guava:guava:18.0'
compile 'org.hamcrest:hamcrest-core:1.3'
compile 'org.hamcrest:hamcrest-library:1.3'
compile 'net.sourceforge.htmlunit:htmlunit:2.15'
compile 'net.sourceforge.htmlunit:htmlunit-core-js:2.15'
compile 'org.apache.httpcomponents:httpclient:4.3.6'
compile 'org.apache.httpcomponents:httpcore:4.3.3'
compile 'org.apache.httpcomponents:httpmime:4.3.6'
compile 'org.ini4j:ini4j:0.5.2'
//Added Lib only
//compile 'com.beust:jcommander:1.29'
compile 'io.appium:java-client:2.1.0'
compile 'io.appium:java-client:3.3.0'
compile 'org.eclipse.jetty:jetty-websocket:8.1.8.v20121106'
compile 'net.java.dev.jna:jna:3.4.0'
compile 'net.java.dev.jna:jna-platform:4.2.0'
compile 'junit:junit-dep:4.11'
compile 'log4j:log4j:1.2.17'
compile 'javax.mail:mail:1.5.0-b01'
compile 'net.sourceforge.nekohtml:nekohtml:1.9.22'
compile 'io.netty:netty:3.5.7.Final'
compile 'com.opera:operadriver:1.5'
compile 'com.codeborne:phantomjsdriver:1.2.1'
compile 'org.apache.poi:poi:3.9'
compile 'org.apache.poi:poi-ooxml:3.9'
compile 'org.apache.poi:poi-ooxml-schemas:3.9'
compile 'com.google.protobuf:protobuf-java:2.4.1'
compile 'com.jayway.android.robotium:robotium-solo:4.3.1'
compile 'milyn:sac:1.3'
compile 'org.seleniumhq.selenium:selenium-java:2.45.0'
compile 'org.seleniumhq.selenium:selenium-server:2.45.0'
compile 'org.seleniumhq.selenium:selenium-support:2.45.0'
compile 'xalan:serializer:2.7.1'
compile 'org.xerial:sqlite-jdbc:3.8.11.1'
compile 'org.testng:testng:6.8.5'
compile 'xalan:xalan:2.7.1'
compile 'xerces:xercesImpl:2.11.0'
compile 'xml-apis:xml-apis:1.4.01'
compile 'org.apache.xmlbeans:xmlbeans:2.3.0'  
compile 'com.relevantcodes:extentreports:2.10'
//compile 'com.relevantcodes:extentreports:2.40.1'
compile 'com.relevantcodes:extentreports:2.41.1'
compile 'com.google.android:android:4.1.1.4'
compile 'com.google.android:support-v4:r7'
compile 'commons-collections:commons-collections:3.2.1'
//Flash
compile 'org.seleniumhq.selenium:selenium:2.0rc2'
compile 'com.googlecode.javacpp:javacpp:0.7'
compile 'org.sikuli:sikuli-api:1.2.0'
//extentreport - Added Lib
//compile 'org.jsoup:jsoup:1.8.3'
//compile 'org.xerial:sqlite-jdbc:3.8.11'
//compile 'org.freemarker:freemarker:2.3.23'
compile 'org.mongodb:mongodb-driver:3.0.4'
compile 'org.testng:testng:6.9.9'
compile 'commons-codec:commons-codec:1.4'




//compile 'org.sikuli:sikuli-core:1.1.0'
//compile 'io.appium:java-client:2.1.0'

//compile group: 'org.eclipse.jetty', name: 'jetty-websocket', version: '8.1.8.v20121106'
//compile group: 'net.java.dev.jna', name: 'jna', version: '3.4.0'
//compile group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '2.45.0'
//compile group: 'org.seleniumhq.selenium', name: 'selenium-server', version: '2.48.2'
//compile group: 'xalan', name: 'serializer', version: '2.7.1'
//compile 'org.seleniumhq.selenium:selenium-java:2.45.0'
//testComplie group='org.apache.commons', module='commons-lang3', version='3.3.2'
//compile 'org.bytedeco:javacv:0.1'
```

}

jar {
   baseName = 'gs-gradle'
    version =  '0.1.0'
}
task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

**Comment by anshooarora** [comment]
Did you recently upgrade to a newer version?  Can you use 2.41.1 and try again?

**Comment by SHASHIJB** [comment]
I have tried using 2.41.1 , still same error message it is throwing .
