### ISSUE TITLE
Getting java.lang.NoSuchMethodError: com.mongodb.MongoClient.getDatabase(Ljava/lang/String;)Lcom/mongodb/client/MongoDatabase error when using extent.x()

### ISSUE THREAD

**Issue by manjunatha056** [anshooarora/extentreports-java#569]
Hi ,

I am getting below error when trying to integrate with extentX

java.lang.NoSuchMethodError: com.mongodb.MongoClient.getDatabase(Ljava/lang/String;)Lcom/mongodb/client/MongoDatabase;
	at com.relevantcodes.extentreports.ExtentX.start(ExtentX.java:50)
	at com.relevantcodes.extentreports.Report.attach(Report.java:314)
	at com.relevantcodes.extentreports.ExtentReports.x(ExtentReports.java:609)
	at com.********.automation.utils.web.ExtentReporterNG.generateReport(ExtentReporterNG.java:34)
	at org.testng.TestNG.generateReports(TestNG.java:1135)
	at org.testng.TestNG.run(TestNG.java:1081)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)

I am Using TestNG Listener and below is the part of the code which i am using in listener.

 extent = new ExtentReports(outputDirectory + File.separator + "TestReport.html", true);
      //  System.out.println(System.getProperty("user.dir")+File.separator+"extent-config.xml");
        extent.loadConfig(new File(System.getProperty("user.dir")+File.separator+"extent-config.xml"));
        //extent.loadConfig(ExtentReports.class, "extent-config.xml");
       // extent.loadConfig(ExtentReports.class, "resources", "extent-config.xml");
        extent.assignProject("XXXXXXXXX");
        extent.x();

Regards
Manjunatha P

**Comment by anshooarora** [comment]
Is the MongoDB server running?
