### ISSUE TITLE
Getting Null pointer exception.

### ISSUE THREAD

**Issue by alihozefa** [anshooarora/extentreports-java#586]
**My code is below** 

ExtentReports report;
	ExtentTest logger;

	@Test
	public void test() {
		report = new ExtentReports("C:\\Development\\extent.html");
		logger = report.startTest("abcd");
		InstantiateDriver.getDriver().get("www.google.co.in");
	}

	@After
	public void reporting(ITestResult result) {

		if (result.getStatus() == ITestResult.FAILURE) {
			test.log(LogStatus.FAIL, result.getThrowable() + "");
		} else if (result.getStatus() == ITestResult.SKIP) {
			test.log(LogStatus.SKIP, "Test skipped " + result.getThrowable());
		} else {
			test.log(LogStatus.PASS, "Test passed");
		}
	}

**_Error_**

**java.lang.NullPointerException**
	at org.junit.internal.runners.JUnit38ClassRunner.makeDescription(JUnit38ClassRunner.java:118)
	at org.junit.internal.runners.JUnit38ClassRunner.getDescription(JUnit38ClassRunner.java:93)
	at org.junit.runner.Runner.testCount(Runner.java:41)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.countTestCases(JUnit4TestClassReference.java:30)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.countTests(RemoteTestRunner.java:487)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:455)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by anshooarora** [comment]
You are using TestNG classes in a Junit environment.  Use TestNG imports instead.

**Comment by alihozefa** [comment]
Thanks anshoo,
But I've been using a complicatd wast Framework which is surrounded by Junit and I can't use TestNG somehow so can we implement extentreport in Junit environment itself? and if answer is yes then what exactly I need to do to prevent above mentioned errors!!
