### ISSUE TITLE
Getting exception while writing test log

### ISSUE THREAD

**Issue by pthewizard** [anshooarora/extentreports-java#626]
Code: 

```
@Test
public void login()
{
try
{
test=extent.createTest("Login Test","Valid Login")
.assignCategory("Smoke Text")
.assignAuthor("Platform Team");
test.log(Status.INFO, "Login Test with. Reseller Id: dist1 User Id: webuser Password: 20162016");
driver.findElement(By.xpath("html/body/div[2]/table/tbody/tr[4]/td/table/tbody/tr[3]/td/fieldset/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table/tbody/tr/td/input")).sendKeys("dist1");
driver.findElement(By.xpath("html/body/div[2]/table/tbody/tr[4]/td/table/tbody/tr[3]/td/fieldset/table/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td/input")).sendKeys("webadmin");
driver.findElement(By.xpath("")).sendKeys("20162016");
driver.findElement(By.xpath("html/body/div[2]/table/tbody/tr[4]/td/table/tbody/tr[3]/td/fieldset/table/tbody/tr[2]/td/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input")).click();
Thread.sleep(5000);
Assert.assertEquals(driver.findElement(By.xpath("html/body/div[2]/table/tbody/tr[2]/td/table/tbody/tr/td[1]/div")).isDisplayed(), true);

}
catch(Exception e)
{
e.printStackTrace();
Assert.assertEquals(false, true);
}
}
```

Exception: 
Note: Bold line in login method is generating the exception
```
java.lang.NullPointerException
at com.relevantcodes.extentreports.Report.lambda$12(Report.java:137)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.relevantcodes.extentreports.Report.lambda$9(Report.java:137)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.relevantcodes.extentreports.Report.collectRunInfo(Report.java:132)
at com.relevantcodes.extentreports.Report.addLog(Report.java:60)
at com.relevantcodes.extentreports.ExtentTest.log(ExtentTest.java:87)
at ExtentReport.login(ExtentReport.java:150)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
at org.testng.TestRunner.privateRun(TestRunner.java:782)
at org.testng.TestRunner.run(TestRunner.java:632)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
at org.testng.SuiteRunner.run(SuiteRunner.java:268)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.run(TestNG.java:1064)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
```

**Comment by anshooarora** [comment]
Can you share the setup code as well?

**Comment by pthewizard** [comment]
I debugged my code and found that test.assignAuthor() method is generating the exception. I didn't figure out why it is doing so.

**Comment by anshooarora** [comment]
Issue fixed

**Comment by pthewizard** [comment]
great
