### ISSUE TITLE
Getting exception while adding screenshot

### ISSUE THREAD

**Issue by pthewizard** [anshooarora/extentreports-java#627]
**I am using the following code:**

        @AfterMethod
	public void afterMethod(ITestResult result) throws IOException
	{
		try
		{
			if(result.getStatus()==ITestResult.SUCCESS)
				test.pass("Passed");
			else
			{
				test.log(Status.FAIL, result.getThrowable());
				test.addScreenCaptureFromPath(captureScreen(result));
			}
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public String captureScreen(ITestResult result) throws IOException
	{
		String path=System.getProperty("user.dir")+"/ExtentReport/Screenshots/";
		File sourceFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
	    File targetFile=new File(path+result.getMethod().getMethodName()+"-Run-"+result.getMethod().getCurrentInvocationCount()+".png");
		FileUtils.copyFile(sourceFile, targetFile);
		return targetFile.getAbsolutePath();
	}

**I debugged the code and found that the test.addScreenCaptureFromPath(captureScreen(result)) is generating the exception.**

**Exception:**

```
java.io.UncheckedIOException: java.net.SocketException: Network is unreachable
	at com.relevantcodes.extentreports.Report.lambda$5(Report.java:78)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.relevantcodes.extentreports.Report.addScreenCapture(Report.java:74)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:224)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:230)
	at ExtentReport.afterMethod(ExtentReport.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
Caused by: java.net.SocketException: Network is unreachable
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.relevantcodes.extentreports.mediastorage.HttpMediaManager.storeCsrfCookie(HttpMediaManager.java:53)
	at com.relevantcodes.extentreports.mediastorage.HttpMediaManager.init(HttpMediaManager.java:46)
	at com.relevantcodes.extentreports.reporter.ExtentXReporter.onScreenCaptureAdded(ExtentXReporter.java:422)
	at com.relevantcodes.extentreports.Report.lambda$5(Report.java:76)
	... 31 more
```

**However the screenshot is taken and displayed in the extent report. But I cannot see the screenshots in the ExtentX server reports. Please help!**

**Comment by anshooarora** [comment]
This feature is functional in the latest ExtentReports and ExtentX commits. Both will be released soon.

**Comment by pthewizard** [comment]
Thanks

**Comment by anshooarora** [comment]
PS.  You can test with the latest master of ExtentReports/ExtentX.  This should be functional.  The below are deprecated though:

1. Email Reporter
2. allow automatic saving of media files relative to the report:

```
htmlReporter.config().setAutoCreateRelativePathMedia(true);
```
