### ISSUE TITLE
Not able to flush the report

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentreports-java#655]
@anshooarora When i call ExtentTestManager.getExtent().flush i get the below error 

```
Oct 19, 2016 10:26:08 PM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> sa.value  [in template "dashboard-view/dashboard-view.ftl" at line 57, column 64]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${sa.value}  [in template "dashboard-view/dashboard-view.ftl" at line 57, column 61]
        - Reached through: #include "dashboard-view/dashboard-vi...  [in template "extent.ftl" at line 45, column 25]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
        at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.include(Environment.java:2072)
        at freemarker.core.Include.accept(Include.java:167)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.process(Environment.java:302)
        at freemarker.template.Template.process(Template.java:325)
        at com.aventstack.extentreports.reporter.ExtentHtmlReporter.flush(ExtentHtmlReporter.java:121)
        at com.aventstack.extentreports.Report$$Lambda$39/544169910.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.aventstack.extentreports.Report.notifyReporters(Report.java:165)
        at com.aventstack.extentreports.Report.flush(Report.java:122)
        at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:257)
        at com.appium.manager.AppiumParallelTest.endLogTestResults(AppiumParallelTest.java:507)
        at com.test.site.UserBaseTest.killServer(UserBaseTest.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Oct 19, 2016 10:26:08 PM com.aventstack.extentreports.reporter.ExtentHtmlReporter flush
SEVERE: Template not found
FreeMarker template error:
The following has evaluated to null or missing:
==> sa.value  [in template "dashboard-view/dashboard-view.ftl" at line 57, column 64]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${sa.value}  [in template "dashboard-view/dashboard-view.ftl" at line 57, column 61]
        - Reached through: #include "dashboard-view/dashboard-vi...  [in template "extent.ftl" at line 45, column 25]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
        at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
        at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.include(Environment.java:2072)
        at freemarker.core.Include.accept(Include.java:167)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.MixedContent.accept(MixedContent.java:54)
        at freemarker.core.Environment.visit(Environment.java:324)
        at freemarker.core.Environment.process(Environment.java:302)
        at freemarker.template.Template.process(Template.java:325)
        at com.aventstack.extentreports.reporter.ExtentHtmlReporter.flush(ExtentHtmlReporter.java:121)
        at com.aventstack.extentreports.Report$$Lambda$39/544169910.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.aventstack.extentreports.Report.notifyReporters(Report.java:165)
        at com.aventstack.extentreports.Report.flush(Report.java:122)
        at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:257)
        at com.appium.manager.AppiumParallelTest.endLogTestResults(AppiumParallelTest.java:507)
        at com.test.site.UserBaseTest.killServer(UserBaseTest.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Oct 19, 2016 10:26:08 PM com.aventstack.extentreports.utils.Writer write
SEVERE: /Users/saikrisv/git/new_appium_parallel/AppiumTestDistribution/target/ExtentReports.html
java.lang.NullPointerException
        at java.io.Writer.write(Writer.java:157)
        at com.aventstack.extentreports.utils.Writer.write(Writer.java:23)
        at com.aventstack.extentreports.reporter.ExtentHtmlReporter.flush(ExtentHtmlReporter.java:130)
        at com.aventstack.extentreports.Report$$Lambda$39/544169910.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.aventstack.extentreports.Report.notifyReporters(Report.java:165)
        at com.aventstack.extentreports.Report.flush(Report.java:122)
        at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:257)
        at com.appium.manager.AppiumParallelTest.endLogTestResults(AppiumParallelTest.java:507)
        at com.test.site.UserBaseTest.killServer(UserBaseTest.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

[HTTP] --> DELETE /wd/hub/session/078d6351-e891-4966-9831-59eef10854f2 {}

```

**Comment by anshooarora** [comment]
This would happen if the system attribute value evaluates to null.  Still, the huge exception should not be thrown.

**Comment by bobby06495** [comment]
May I know what could be the solution I am getting the same error

**Comment by pgaurav2610** [comment]
I am also getting somewhat same exception while flush. Below is the stack trace -

 ]Dec 24, 2018 5:35:09 PM com.aventstack.extentreports.reporter.ExtentHtmlReporter flush
SEVERE: Template not found
freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: [freemarker.cache.ClassTemplateLoader.toString() failed: java.lang.NoClassDefFoundError: freemarker/cache/TemplateLoaderUtils].
	at freemarker.template.Configuration.getTemplate(Configuration.java:2797)
	at freemarker.template.Configuration.getTemplate(Configuration.java:2599)
	at com.aventstack.extentreports.reporter.ExtentHtmlReporter.flush(ExtentHtmlReporter.java:138)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.aventstack.extentreports.Report.notifyReporters(Report.java:263)
	at com.aventstack.extentreports.Report.flush(Report.java:185)
	at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:281)


Is there any solution to this problem ?

Extent version i am using - 3.1.5
