### ISSUE TITLE
java.io.NotSerializableException: com.mongodb.MongoCollectionImpl

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports-java#802]
Anshoo,
I am using client server model test automation framework. The ExtentTest object needs to be passed from client to server. I added Serializable to the following classes, but i stuck at the above error.
ExtentReports.java, Report.java, TestAttributeTestContextProvider.java, ExtentHtmlReporter.java, ExceptionTestContectImpl.java, ExtentHtmlReporterConfiguration.java, ExtentXReporterConfiguration.java, ExtentXReporter.java

I tried to find mongo db connection related class, but could not.

When i am searching in google, i found the following URL. Can you please check whether it helps in resolving this issue?

http://stackoverflow.com/questions/34593832/java-io-notserializableexception-com-mongodb-mongocollectionimpl-error

Appreciate your quick help.

**Exception info:**
java.rmi.MarshalException: error marshalling arguments; nested exception is: 
	java.io.NotSerializableException: com.mongodb.MongoCollectionImpl
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:158)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
	at com.sun.proxy.$Proxy3.invokeAdapter(Unknown Source)
	at com.arcot.test.adapter.RemoteRequestSender.invokeAdapter(RemoteRequestSender.java:67)
	at com.arcot.test.framework.TestScenarioRunner.callAdapter(TestScenarioRunner.java:649)
	at com.arcot.test.framework.TestScenarioRunner.runTestScenario(TestScenarioRunner.java:345)
	at com.arcot.test.framework.TestTypeRunner.runAllTestScenarios(TestTypeRunner.java:475)
	at com.arcot.test.framework.Gift.run(Gift.java:522)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.NotSerializableException: com.mongodb.MongoCollectionImpl
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1777)
	at java.util.HashMap.writeObject(HashMap.java:1354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at sun.rmi.server.UnicastRef.marshalValue(UnicastRef.java:294)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:153)
	... 9 more
error marshalling arguments; nested exception is: 
	java.io.NotSerializableException: com.mongodb.MongoCollectionImpl

Thanks

**Comment by gsaimadhu** [comment]
Anshoo, any comments on this issue?
I am blocked on upgrading extent reports from 2.42 to 3.X.

**Comment by virenv** [comment]
com.mongodb.MongoCollectionImpl is not Serializable class. You cannot pass it to the server by writing a serialized stream. Here you can see the[ class signatures](https://github.com/mongodb/mongo-java-driver/blob/master/driver/src/main/com/mongodb/MongoCollectionImpl.java)

The only thing I can suggest you is that create a thin wrapper around com.mongodb.MongoCollectionImpl and implement Serializable on the wrapper. That way you can do around this problem. 

However, if you are at this point then I would suggest that let you test framework talk to the server in custom data structures instead of directly relying on the MongoCollectionImpl class.

I hope it helps. I am closing this issue as it is not related to Extent report. Feel free to ask more questions.
