### ISSUE TITLE
addScreenCaptureFromPath returning java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentreports-java#812]
relativepath is .\screenshots\en_US\LATENCY_TEST_TestStep_1_DataSet_1_open_2_1641.jpeg
**logEx.get().log(Status.INFO, ""+ logEx.get().addScreenCaptureFromPath(relativePath));**

java.lang.ArrayIndexOutOfBoundsException: 0
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.storeCsrfCookie(HttpMediaManager.java:61)
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.init(HttpMediaManager.java:48)
	at com.aventstack.extentreports.reporter.ExtentXReporter.initMedia(ExtentXReporter.java:531)
	at com.aventstack.extentreports.reporter.ExtentXReporter.onScreenCaptureAdded(ExtentXReporter.java:497)
	at com.aventstack.extentreports.Report.lambda$5(Report.java:93)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.aventstack.extentreports.Report.addScreenCapture(Report.java:91)
	at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:1099)
	at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:1106)
	at com.ca.generic.automation.gui.ObjectPage.captureScreenShot(ObjectPage.java:2146)

**Comment by anshooarora** [comment]
This error is from the Http manager which is responsible for uploading images to the server.  Is the server up at the time of test execution?

**Comment by gsaimadhu** [comment]
Yes Anshoo,
server is up at the time of execution.

**Comment by anshooarora** [comment]
What are versions of api and server?

**Comment by gsaimadhu** [comment]
Extent Reports 3.0.3
ExtentX 1.0.1

**Comment by anshooarora** [comment]
I am unable to reproduce this..  Is the server on the same machine as the client, or on a different one?  Do you have admin rights on this machine?  Need to figure out how to reproduce this.  There was another user who had this issue and it turned out to be because of insufficient rights on the target machine.

**Comment by virenv** [comment]
cookie = response.getHeaders("set-cookie")[0].getValue(); this code at line 61 is anyway not doing anything? Cookie retrieved is not being used in the method. Do we require this line.

And this line is capable of throwing Index out of bound in case when response.getHeaders("set-cookie") returns an empty header array.

As this is an httprequest, I would believe that we should safe guard against empty "set-cookie" header in this code only.

@anshooarora  any historical context around this?

**Comment by anshooarora** [comment]
cookie is used in the post along with csrf otherwise server will not accept images. The set-cookie shouldn't be empty and if it is, there wouldn't be a way for a successful handshake with the client.

**Comment by virenv** [comment]
Then in that case we should be putting a sort of assert and throwing with a more readable message.

Root cause is still not know then.

**Comment by anshooarora** [comment]
Yeah.. i was thinking the same and introduce an assertion error if the array has 0 elements. I havent been able to figure a root cause yet.

**Comment by email2vimalraj** [comment]
@anshooarora : Hope this issue had been resolved as part of v3.0.5. If so, can we please go ahead and close this.

**Comment by anshooarora** [comment]
Yes, this issue can now be closed.  Thanks.
