### ISSUE TITLE
Screenshots not uploaded to extentx server

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentreports-java#909]
Jul 11, 2017 11:04:34 AM com.aventstack.extentreports.mediastorage.HttpMediaManager storeMedia
--
**11-Jul-2017 16:34:31 | WARNING: Unable to upload file to server**

I am running the the test cases from an user admin that has it's own environment env.conf file in centos.

**Comment by anshooarora** [comment]
Do you get any other errors besides this?

**Comment by prasanta-biswas** [comment]
No only this exception

```
Jul 26, 2017 1:27:24 PM com.aventstack.extentreports.mediastorage.HttpMediaManager storeCsrfCookie
SEVERE: Unable to parse x-csrf-token
javax.script.ScriptException: TypeError: Cannot call undefined in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:455)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:439)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:401)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:397)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:152)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.storeCsrfCookie(HttpMediaManager.java:81)
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.init(HttpMediaManager.java:48)
	at com.aventstack.extentreports.reporter.ExtentXReporter.initMedia(ExtentXReporter.java:588)
	at com.aventstack.extentreports.reporter.ExtentXReporter.initOnScreenCaptureAdded(ExtentXReporter.java:551)
	at com.aventstack.extentreports.reporter.ExtentXReporter.onScreenCaptureAdded(ExtentXReporter.java:530)
	at com.aventstack.extentreports.Report.lambda$addScreenCapture$7(Report.java:119)
	at com.aventstack.extentreports.Report$$Lambda$36/1775383190.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.aventstack.extentreports.Report.addScreenCapture(Report.java:117)
	at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:1105)
	at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:1112)
	at com.seamless.ers.standard.testclass.agentportal.ErsStdAgentPortal.tearDownMethod(ErsStdAgentPortal.java:100)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.TestNG.privateMain(TestNG.java:1434)
	at org.testng.TestNG.main(TestNG.java:1403)
Caused by: <eval>:1 TypeError: Cannot call undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookupTypeError(Undefined.java:128)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:100)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:94)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:149)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:233)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:636)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:437)
	... 41 more

Jul 26, 2017 1:27:25 PM com.aventstack.extentreports.mediastorage.HttpMediaManager storeMedia
```
I am using latest versions of extent reports and extentx server. This is not happening if I run from my local user or root user in any vm with java. It is only happening from admin user which has its own environment set.

**Comment by hemano** [comment]
Any update on this?

**Comment by anshooarora** [comment]
The issue is with csrf not matching.  Are you able to access the server from this machine, and is the csrf available when you open the "/csrfToken" route?

PS.  The replacement for ExtentX, called maetri will be available very soon.  Sample here:  http://maetri.herokuapp.com/.
