### ISSUE TITLE
When trying to run extentx, I am getting the following error: java.lang.NoClassDefFoundError: com/mongodb/MongoClient

### ISSUE THREAD

**Issue by mandarin77** [anshooarora/extentreports-java#942]
## Summary

I have been using Extent reports for almost a year now. I am now trying to use Extentx. I set up node.js and mongo db and they seem to be set up correctly, however, when I try to run a test with the newly added Extentx commands, it seems to be giving me this error.

java.lang.NoClassDefFoundError: com/mongodb/MongoClient

## Sample
I placed this in a test case class that has been working prior.

extent.assignProject("AppCentral");
extent.x();

[TestNG] Running:
  C:\Selenium\Appcentral\test.xml

C:\Users\test\Desktop\test.html
Starting ChromeDriver 2.29.461591 (62ebf098771772160f391d75e589dc567915b233) on port 16099
Only local connections are allowed.
Sep 02, 2017 9:23:48 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Sep 02, 2017 9:23:50 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
C:\Users\test\Desktop\test.html
java.lang.NoClassDefFoundError: com/mongodb/MongoClient
	at com.relevantcodes.extentreports.ExtentX.<init>(ExtentX.java:293)
	at com.relevantcodes.extentreports.ExtentReports.x(ExtentReports.java:571)
	at AppCentralScenarios.App_Central_Warm_Up.TEST_NAME(test.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.ClassNotFoundException: com.mongodb.MongoClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more

===============================================
Suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

**Comment by anshooarora** [comment]
Your version?  Have you added all the correct dependencies?

**Comment by mandarin77** [comment]
This issue can be closed. I needed to add the dependencies.
